name: docker-push-image

on:
  workflow_dispatch:
  push:
    branches:
      - 'production'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: push image to hub.docker
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:DrinkerAPI"
          push: true
          tags: kszekosz11/drinker-app:latest
  deploy:
    needs: docker
    name: deploy to fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -a drinker --remote-only